# Get all trips
GET http://localhost:8080/trips
Accept: application/json

###

#Get trip by id
GET http://localhost:8080/trips/6987d57c0be5bd4c96544d0e
Accept: application/json

###

# Get all attractions
GET http://localhost:8080/attractions
Accept: application/json

###

#Get attractions by id
GET http://localhost:8080/attractions/6987c1c7e7337a2f7ebf35ad
Accept: application/json

###

#insert trip
POST http://localhost:8080/trips/
Content-Type: application/json
Accept: application/json

{
    "name": "Winter Trip",
    "startDate": "2027-11-21",
    "endDate": "2027-11-28",
    "parkList": ["Magic Kingdome", "Hollwood Studios","EPCOT"],
    "hotel": "Polly",
    "budget": 7000,
    "notes": "See if there are parties available"
}

###

#insert attraction
POST http://localhost:8080/attractions/
Content-Type: application/json
Accept: application/json

{
    "name": "Moana Water Experiance",
    "park": "EPCOT",
    "waitTime": 5,
    "rideType": "Walk through experiance"
}

###

#edit trip
PUT http://localhost:8080/trips/6987f26c95d191717375eed4
Content-Type: application/json
Accept: application/json

{
    "name": "Spring Break",
    "startDate": "2026-03-15",
    "endDate": "2026-03-21",
    "parkList": ["Magic Kingdome", "Hollwood Studios", "EPCOT"], 
    "hotel": "Polly",
    "budget": 6000,
    "notes": "Remember to book reservations at Boma"   
}

###

#edit attraction
PUT http://localhost:8080/attractions/69a2eddce060a96d0bfb0522
Content-Type: application/json
Accept: application/json

{
    "name": "Moana Water Experiance",
    "park": "EPCOT",
    "waitTime": 15,
    "rideType": "Walk throught experiance"
}

###

#delete trip
DELETE http://localhost:8080/trips/6987f26c95d191717375eed4

Accept: application/json



###

#delete attraction
DELETE http://localhost:8080/attractions/69a2eb2ee17d086a4600023d

Accept: application/json




